version: "3"
services:
  name:
    container_name: crontab-ui
    image: alseambusher/crontab-ui:latest
    volumes:
      - ./backup:/crontabs
    ports:
      - "9080:8000"
    environment:
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PWD=admin
    restart: always
